---
- hosts: webservers
  remote_user: root
  tasks:

    - name: Install web-ssms
      npm:
        name: web-ssms
        global: no
        path: /opt/web-ssms
        version: latest

    - name: "setup index.js file"
      command: "echo require\\(\\'web-ssms\\'\\) >> /opt/web-ssms/index.js"

    - name: stop web-ssms
      command: "pm2 stop web-ssms"
      ignore_errors: yes

    - name: restart web-ssms
      command: "pm2 start /opt/web-ssms/index.js -n web-ssms"
      ignore_errors: no
...